framework:
    cache:
        prefix_seed: agicr
        app: cache.adapter.redis
        default_redis_provider: "%env(REDIS_DSN)%"
        pools:
            cache.rate_limiter:
                adapter: cache.app
